### ISSUE TITLE
Cannot deploy my app after upgrading to v10 today

### ISSUE THREAD

**Issue by oreoero** [microsoft/vscode-azureresourcegroups#999]
After updating to V10 today, I cannot deploy my azure function app, with Internal error: Expected value to be neither null nor undefined: newSiteName

**Comment by alexweininger** [comment]
Hi, could you revert to Azure Resources v0.9.9 and try again? You can do so by selecting "Install specific version..."

<img width="668" alt="Image" src="https://github.com/user-attachments/assets/5e8bac27-fe3d-4168-830a-6e86fa091ca9" />

The changes released in v10 _should_ be unrelated to deploying a function app. Reverting and trying again will tell us if that's truly the case.

**Comment by oreoero** [comment]
Thanks for the prompt reply. 

Yes it worked after falling back.

**Comment by alexweininger** [comment]
I'm wondering if it worked because you rolled back or because you tried it again. If you could update to v10 and try deploying again that would help me a lot.

**Comment by oreoero** [comment]
I tried again, it does not work on 0.10.0 but it works 0.9.0, I restarted vscode in between.

**Comment by alexweininger** [comment]
Thanks. What entry point for deploy are you using? Could you give me detailed repro steps?

**Comment by HAL377** [comment]
I have the exact same problem when deploying my PowerShell based function app today after updating Azure Resources extensions.. I reverted to the previous release of Azure Resources and its working fine now.

**Comment by SussexGooner** [comment]
I had a similar problem deploying a static webpage through VS Code. It came up with an error message about not being able to find the $web blob for the storage account.  I reverted to the previous version this morning and the problem went away.

**Comment by alexweininger** [comment]
The fix for this issue is to change the Microsoft Authentication Implementation setting to MSAL
![Image](https://github.com/user-attachments/assets/c02db8f1-1091-41ec-a6d3-564ff1cfa0f1)
This is the default setting in the current insiders version.

The issue only happens in stable or when this setting is set to Classic.

**Comment by alexweininger** [comment]
I have a fix in the works. Hoping to release the full fix today. https://github.com/microsoft/vscode-azureresourcegroups/pull/1000

**Comment by SussexGooner** [comment]
Thanks for the quick response. I am not sure where to set this.

**Comment by alexweininger** [comment]
We just released [Azure Resources v.0.10.1](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.10.1) which includes the fix for this issue.

**Comment by oreoero** [comment]
Thanks a lot, I confirm v.0.10.1 works on my end.

**Comment by SussexGooner** [comment]
I still get the error: Could not find $web blob container for storage account ...

**Comment by alexweininger** [comment]
> I still get the error: Could not find $web blob container for storage account ...

@SussexGooner this sounds like a separate issue. Can you file a new one?
